/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_package;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Vishwam
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    Connection con;
    public admin() {
        initComponents();
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/library","root","Vishup08");
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }
        
        LoginPage.setVisible(true);
        MainPage.setVisible(false);
        BooksPage.setVisible(false);
        OrdersPage.setVisible(false);
        
        JTableHeader header = OrdersTable.getTableHeader();
        TableColumnModel model = header.getColumnModel();
        TableColumn column = model.getColumn(0);
        column.setHeaderValue("Order ID");
        header.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        LoginPage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UsrT = new javax.swing.JTextField();
        PwdT = new javax.swing.JTextField();
        LoginB = new javax.swing.JButton();
        MainPage = new javax.swing.JPanel();
        addBookB = new javax.swing.JButton();
        OrdersB = new javax.swing.JButton();
        BooksPage = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BookNameT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bookgenret = new javax.swing.JTextField();
        bookDoneB = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        OrdersPage = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrdersTable = new javax.swing.JTable();
        OrderOkButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Username: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Password: ");

        UsrT.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        PwdT.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        LoginB.setText("Done");
        LoginB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginPageLayout = new javax.swing.GroupLayout(LoginPage);
        LoginPage.setLayout(LoginPageLayout);
        LoginPageLayout.setHorizontalGroup(
            LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPageLayout.createSequentialGroup()
                .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPageLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginPageLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(UsrT, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(LoginPageLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(PwdT, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(LoginPageLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(LoginB)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        LoginPageLayout.setVerticalGroup(
            LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPageLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(UsrT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PwdT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(LoginB)
                .addGap(48, 48, 48))
        );

        addBookB.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        addBookB.setText("Add a book ");
        addBookB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookBActionPerformed(evt);
            }
        });

        OrdersB.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        OrdersB.setText("Orders");
        OrdersB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdersBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPageLayout = new javax.swing.GroupLayout(MainPage);
        MainPage.setLayout(MainPageLayout);
        MainPageLayout.setHorizontalGroup(
            MainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPageLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(MainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBookB)
                    .addGroup(MainPageLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(OrdersB)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        MainPageLayout.setVerticalGroup(
            MainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPageLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(addBookB)
                .addGap(18, 18, 18)
                .addComponent(OrdersB)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Name: ");

        BookNameT.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Genre:");

        bookgenret.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        bookDoneB.setText("Done");
        bookDoneB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookDoneBActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setText("Add Book");

        javax.swing.GroupLayout BooksPageLayout = new javax.swing.GroupLayout(BooksPage);
        BooksPage.setLayout(BooksPageLayout);
        BooksPageLayout.setHorizontalGroup(
            BooksPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BooksPageLayout.createSequentialGroup()
                .addGroup(BooksPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BooksPageLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(BooksPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BooksPageLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(21, 21, 21)
                                .addComponent(bookgenret, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BooksPageLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(BookNameT, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(BooksPageLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(bookDoneB))
                    .addGroup(BooksPageLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel6)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        BooksPageLayout.setVerticalGroup(
            BooksPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BooksPageLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addGap(74, 74, 74)
                .addGroup(BooksPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(BookNameT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BooksPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(bookgenret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(bookDoneB)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        OrdersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Customer name", "Book id", "Customer id", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(OrdersTable);

        OrderOkButton.setText("OK");
        OrderOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderOkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OrdersPageLayout = new javax.swing.GroupLayout(OrdersPage);
        OrdersPage.setLayout(OrdersPageLayout);
        OrdersPageLayout.setHorizontalGroup(
            OrdersPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrdersPageLayout.createSequentialGroup()
                .addGroup(OrdersPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OrdersPageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OrdersPageLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(OrderOkButton)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        OrdersPageLayout.setVerticalGroup(
            OrdersPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrdersPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OrderOkButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(LoginPage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(MainPage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(BooksPage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(OrdersPage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MainPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(BooksPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(OrdersPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MainPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(BooksPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(OrdersPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>                        

    private void LoginBActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if(UsrT.getText().equals("admin") && PwdT.getText().equals("admin"))
        {
            LoginPage.setVisible(false);
            MainPage.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Wrong Username/Password");
        }
    }                                      

    private void addBookBActionPerformed(java.awt.event.ActionEvent evt) {                                         
        BooksPage.setVisible(true);
        MainPage.setVisible(false);
    }                                        

    private void OrdersBActionPerformed(java.awt.event.ActionEvent evt) {                                        
        OrdersPage.setVisible(true);
        MainPage.setVisible(false);
        refreshTable();
    }                                       
    public void refreshTable(){
        int ind=0;
        try{
        Statement st=con.createStatement();
        Statement st1=con.createStatement();
        ResultSet rs=st.executeQuery("select * from orders;");
        while(rs.next())
        {
            if(!(rs.getBoolean("seen")))
            {
                OrdersTable.setValueAt(Integer.toString(rs.getInt("order_id")), ind, 0);
                OrdersTable.setValueAt(Integer.toString(rs.getInt("book_id")), ind, 1);
                OrdersTable.setValueAt(Integer.toString(rs.getInt("cust_id")), ind, 2);
                OrdersTable.setValueAt(rs.getString("Address"), ind, 3);
                ind++;
            }
        }
    }catch(Exception e)
    {
        e.printStackTrace();
    }
    }
    private void bookDoneBActionPerformed(java.awt.event.ActionEvent evt) {                                          
        try{
            Statement st=con.createStatement();
            st.executeUpdate("insert into books1(sname, genre) values('"+BookNameT.getText()+"','"+bookgenret.getText()+"');");
            ResultSet rs = st.executeQuery("select(max(sid)) from books1;");
            rs.next();
            int book_id = rs.getInt(1);
            JOptionPane.showMessageDialog(rootPane,"Book added successfully!\nDetails:"
                    +"Book ID: " + book_id + 
                    "\nBook Name:"+BookNameT.getText()+"\nGenre: "+bookgenret.getText());
            MainPage.setVisible(true);
            BooksPage.setVisible(false);
        } catch(Exception e){
            System.out.println(e);
        }
    }                                         

    private void OrderOkButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        MainPage.setVisible(true);
        OrdersPage.setVisible(false);
        refreshTable();
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField BookNameT;
    private javax.swing.JPanel BooksPage;
    private javax.swing.JButton LoginB;
    private javax.swing.JPanel LoginPage;
    private javax.swing.JPanel MainPage;
    private javax.swing.JButton OrderOkButton;
    private javax.swing.JButton OrdersB;
    private javax.swing.JPanel OrdersPage;
    private javax.swing.JTable OrdersTable;
    private javax.swing.JTextField PwdT;
    private javax.swing.JTextField UsrT;
    private javax.swing.JButton addBookB;
    private javax.swing.JButton bookDoneB;
    private javax.swing.JTextField bookgenret;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}
